### ISSUE TITLE
Permanently deleting an entry from persistant storage

### ISSUE THREAD

**Issue by soubhikchatterjee** [nedbhq/nedb-core#9]
I am using nedb in one of my projects. It seems to be matching my needs so far. I see one issue though, when trying to delete a record, instead of deleting the entire record, it does a partial deletion. i.e. it deletes the record and adds $$deleted: true.

`{"$$deleted":true,"_id":"5ff56dece70e4d331ca9d724"}
`

Can the record be deleted permanently?
 
This is my code:
```
  db.remove({ name: doc.name }, {}, function (err, numRemoved) {
        // numRemoved = 1
      });
```

**Comment by JamesMGreene** [comment]
This is intentional if you read through the documentation: https://github.com/nedbhq/nedb-core#persistence

These records will be cleaned up the next time the database compacts (typically by running auto-compaction).
